# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    volumes:
      - 'mysql_data:/var/lib/mysql'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: game
      MYSQL_USER: user
      MYSQL_PASSWORD: 123

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql_data:
    driver: local
    
networks:
  default:
    external:
      name: game_network